[FilterPlugin]
; Files and folders to include absolutely in the final build
/SharedFolderColor.uplugin
/README.md
/LICENSE
/Resources/...
/Source/...

; Files or folders to exclude from packaging
-.git/...
-.vs/...